---
# tasks/install_prometheus.yml

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"
  # Завантаження Prometheus

- name: Extract Prometheus
  unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/opt"
    remote_src: yes
  # Розпакування Prometheus

- name: Copy Prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml"
  notify: "restart prometheus"
  # Копіювання конфігураційного файлу Prometheus

- name: Setup Prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: "/etc/systemd/system/prometheus.service"
  notify: "restart prometheus"
  # Налаштування служби systemd для Prometheus

- name: Start Prometheus service
  systemd:
    name: prometheus
    enabled: yes
    state: started
  # Запуск служби Prometheus
