---
# tasks/install_grafana.yml

- name: Add Grafana repository
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  # Додавання репозиторію Grafana

- name: Install Grafana
  apt:
    name: grafana
    state: latest
  when: ansible_os_family == "Debian"
  # Встановлення Grafana

- name: Configure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: grafana
    group: grafana
    mode: '0640'
  notify: restart grafana
  # Конфігурація Grafana з використанням шаблону

- name: Copy Grafana provisioning files
  copy:
    src: "{{ playbook_dir }}/files/grafana/provisioning"
    dest: /etc/grafana/provisioning
    mode: '0755'
    owner: grafana
    group: grafana
  notify: restart grafana
  # Копіювання файлів налаштувань Grafana для автоматичного розпізнавання джерел даних

- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started
  # Включення та запуск служби Grafana
